### PR TITLE
feat: add subsections pagination to section template

### PR DESCRIPTION
**Pull request by TetianaG**
## Description

Removing "See all" subsections and adding subsections pagination to Section template.

## Checklist

- [x] :green_book: all commit messages follow the [conventional commits](https://conventionalcommits.org/) standard
- [x] :nail_care: SASS files are compiled
- [x] :arrow_left: changes are compatible with RTL direction
- [x] :wheelchair: changes are accessible
- [x] :memo: changes are tested in Chrome, Firefox, Safari and Edge
- [x] :iphone: changes are responsive and tested in mobile
- [ ] :+1: PR is approved by @zendesk/vikings

### CODE REVIEW

**Comment by augustocravosilva** [comment]
I believe there's some related JS and CSS that can be removed as well

**Comment by augustocravosilva** [comment]
Please re-write the existing pagination as `{{pagination "section.articles"}}` to be consistent

**Review by augustocravosilva — APPROVED** [review]
Be aware that this will cause up to _max subsections per page_ (30?) to show right away instead of 6

**Comment by TetianaG** [comment]
The current limit is 20 subsections.

**Comment by luis-almeida** [comment]
> The current limit is 20 subsections.

Yes but from what I understand the JavaScript snippet was collapsing the list of subsections to only show up to 6.

**Comment by TetianaG** [comment]
> > The current limit is 20 subsections.
> 
> Yes but from what I understand the JavaScript snippet was collapsing the list of subsections to only show up to 6.

Yes, but the maximum number of possible subsections is 20 right now.

**Pull request merged**
