### PR TITLE
[HCJ-1507] Add skip to main content link

### PR DESCRIPTION
**Pull request by vecerek**
A "Skip to main content" button helps the users to skip all the repetitive links in the header of a page. If well targeted, it can save a lot of time navigating to the main content of the page. The button was designed to be theme-neutral just like all the "admin" components we have and it looks like this:

skip_to_main_content

Regarding where the button leads in the different pages, look at the table here:

| Page | Main content |
| ----- | ------------- |
| Home page | Search bar |
| Article page | Article content |
| Search page | First result |
| Community add new post page | Form |
| Request page | Form |
| My activities | First result |
| My profile | Edit profile button |
| Section page | First result |
| Category page | First result |
| Community post list page | First result |
| Community post page | Post content |
| Community topic list page | First result |
| Community topic page | First result |
| Contributions page | First result |
| Error page | Take me back to home page or sign in, etc. link |
| Requests page | Search bar |
| Subscriptions page | First result |

### References

* https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/mouse-and-keyboard-events/skip-to-main-content/

### Risks
Low - the skip to main content button may be visible when it should not be in different browsers 🤷‍♂

### CODE REVIEW

**Comment by vecerek** [comment]
@VilhelmNielsen @luis-almeida I've just rebased the branch due to some conflicts. The strings should also be ready for use, AFAICT. Is there anything else I should do? Bumping the version in the manifest, maybe?

**Comment by luis-almeida** [comment]
@vecerek would be nice to include the version bump as part of the PR
We'll make sure to push this out when it gets merged  👍

**Comment by vecerek** [comment]
@luis-almeida addressed in https://github.com/zendesk/copenhagen_theme/pull/127/commits/f141d1ef468e7dc540b292dfef244e258509fd70.

**Comment by VilhelmNielsen** [comment]
@vecerek We've fixed the failing Lighthouse job on `master`, care to rebase one more time? 🙏

**Comment by vecerek** [comment]
@VilhelmNielsen done 🙂

**Comment by vecerek** [comment]
🎉🎆

**Pull request merged**
