### PR TITLE
Screen reader improvements

### PR DESCRIPTION
**Pull request by ralfpatric**
## Description

This PR introduces some improvements that will enhance the usage of screen readers. Prior to this change the meta-data elements were interpreted as list items.

## Checklist

- [x] :green_book: all commit messages follow the [conventional commits](https://conventionalcommits.org/) standard
- [x] :nail_care: SASS files are compiled
- [ ] :arrow_left: changes are compatible with RTL direction
- [x] :wheelchair: changes are accessible
- [ ] :memo: changes are tested in Chrome, Firefox, Safari and Edge
- [ ] :iphone: changes are responsive and tested in mobile
- [ ] :+1: PR is approved by @zendesk/vikings

### CODE REVIEW

**Review by Anifacted — CHANGES_REQUESTED** [review]
Looks like the SCSS files are not compiled.

**Review by Anifacted — APPROVED** [review]

**Review by anpa — COMMENTED** [review]
Curious, why is it better in terms of a11y to interpret meta-data elements as `span` instead of a list of items?

(thanks for giving some a11y love to the theme ❤️ )

**Comment by ralfpatric** [comment]
The reason here is that some screen readers will announce that the user is traversing a list, where in reality it's not a list but just information about the post.

**Pull request merged**
