### PR TITLE
Updatign the article template to use the new edited_at property

### PR DESCRIPTION
**Pull request by rmcgrew**
Updating the article template for the new edited_at property

@ilkkao @aliciacatalina

### CODE REVIEW

**Comment by aliciacatalina** [comment]
Do we need to update documentation too? https://developer.zendesk.com/apps/docs/help-center-templates/objects#article-object

**Comment by luis-almeida** [comment]
I can see documentation has been updated in the same PR where we added support for `edited_at`:
https://github.com/zendesk/help_center/pull/15229/files#diff-081d6c4a1938144617b42c40ed5fe354R49

I believe this hasn't been reviewed and published in the developer website though.
Definitely a good catch by @aliciacatalina. Would be nice to have this new prop visible in the docs.

**Comment by aliciacatalina** [comment]
So before, with the updated_at an updated article would show like this:
screen shot 2018-01-18 at 10 37 58
 The date it was updated at, and the string updated, because we have a conditional in the template, if I apply the change in this PR to the template, the result is:
screen shot 2018-01-18 at 10 42 43
Because the `edited_at` and the `created_at` are the same, is this what we want to display?
@rmcgrew

**Comment by rmcgrew** [comment]
If the translation hasn't been edited, then yes. So I would guess the update 1 year ago was something like a vote, etc. that wouldn't be considered an edit and we'd still show that original date.

Here's what I see for an article that I've edited. 
screen shot 2018-01-18 at 10 48 47

**Pull request merged**
