### PR TITLE
a11y: Dropdowns

### PR DESCRIPTION
**Pull request by albertfdp**
## Description

This PR refactors the existing dropdown component and aligns it with [Navigation Menubar](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/), [Menubar](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-editor/), and [Menu button](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-links/)

- It expands keyboard support to `Home`, `End` and `Character` key. 
- It automatically creates ids for toggle and menu when not present and uses them for `aria-controls` and `aria-labelledby` as per Menu button spec.
- It moves the `aria-expanded` attribute to the toggle as per spec.
- It supports also targetting `role=menuitemradio`, to better handle menus where there is an existing selection. It updates the templates as appropiate. 

The PR also does minor updates to theme to better align with Garden styles. 

## Screenshots

Screenshot 2023-07-18 at 14 51 10

## Checklist

- [x] :green_book: all commit messages follow the [conventional commits](https://conventionalcommits.org/) standard
- [x] :arrow_left: changes are compatible with RTL direction
- [x] :wheelchair: Changes to the UI are [tested for accessibility](./../README.md#accessibility-testing) and compliant with [WCAG 2.1](https://www.w3.org/TR/WCAG21/).
- [x] :memo: changes are tested in Chrome, Firefox, Safari and Edge
- [x] :iphone: changes are responsive and tested in mobile
- [ ] :+1: PR is approved by @zendesk/vikings

### CODE REVIEW

**Review by luis-almeida — APPROVED** [review]
Looks good! When the required api update is ready 👍🏼

**Review by luis-almeida — COMMENTED** [review]
Refactor and tests look good, so no comments there 👍🏼 

A couple of points:
- Can we colocate the spec file with the source code?
- Nit: no need to check in `scipt.js` and `style.css` as these are rebuilt upon every merge.

**Comment by albertfdp** [comment]
@luis-almeida okay! I have now moved the test file next to the component

**Pull request merged**
